Algoritmo "Celsius e Fahrenheit- Atv.05"
//
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 30/01/2024
Var
// Seção de Declarações das variáveis 
gc, gf: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Digite a temperaturaem Graus Celsius:")
leia(gc)
gf<-(gc*9/5)+32
escreva("A temperatura em Fahrenheit é:")

Fimalgoritmo