Algoritmo "Cálculo preço final"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 06/02/2024
Var
// Seção de Declarações das variáveis 
banana, valor: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva(" Digite a quantidade de bananas desejadas:")
leia(banana)
valor <- (banana*0.75)
escreva(" O valor total a ser pago é de:", valor)
leia(valor)

Fimalgoritmo