Algoritmo "leia e some"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 05/03/2024
Var
// Seção de Declarações das variáveis 
soma, valor: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
soma <- 0
enquanto soma <= 50 faca
escreval(" Digite um numero determinado:")
leia(valor)
soma <- soma + valor
fimenquanto
escreval("O valor é igual a:", soma)


Fimalgoritmo