Algoritmo "leitor de numeros inteiros"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 05/03/2024
Var
// Seção de Declarações das variáveis 
contador, n: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
contador <- 0
escreval(" Digite um primeiro numero inteiro:")
leia(n)
contador <- contador + 1
escreval(" Digite um segundo numero inteiro:")
se contador <= 0 entao



Fimalgoritmo