Algoritmo "Numeros ímpares 100 e 200"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 05/03/2024
Var
// Seção de Declarações das variáveis 
n: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva(" Digite um numero desejado:")
leia(n)
n <- 101
enquanto n <= 200 faca
escreva("Numero Ímpar!")
n <- n + 2
fimenquanto

Fimalgoritmo