Algoritmo "Sistema de Cadastro- Atv.02"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 30/01/2024
Var
// Seção de Declarações das variáveis
nome, idade, cidade: caractere




Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreva("Digite seu nome:")
leia(nome)
escreva("Digite sua idade:")
leia(idade)
escreva("Digite sua cidade:")
leia(cidade)
escreva(" Cadastro efetuado!!")


Fimalgoritmo