Algoritmo "S dos Números"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 06/02/2024
Var
// Seção de Declarações das variáveis 
n01, n02, s: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 escreva(" Digite um primeiro número")
 leia(n01)
 escreva(" Digite um segundo número")
 leia(n02)
 escreva(" Soma final é:" , n01+n02)

Fimalgoritmo