Algoritmo "Par ou Impar- Atv.04"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 30/01/2024
Var
// Seção de Declarações das variáveis 
n:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva(" Digite um número:")
leia(n)
se (n % 2 = 0) entao
    escreva("numero é par!")
senao
escreva("numero é impar!")
fimse

Fimalgoritmo